server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db1805?userSSL=false
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource

    jpa:
      database: mysql
      hibernate:
        ddl-auto: update
